// <auto-generated />
namespace EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Version_13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version_13));
        
        string IMigrationMetadata.Id
        {
            get { return "201703140821541_Version_1.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
